export enum Dialog {
    CONFIRM_ACTION = 'CONFIRM_ACTION',
    CREATE_CHANNEL = 'CREATE_CHANNEL',
    TEXT_INPUT = 'TEXT_INPUT',
    ASSIGN_ROLE = 'ASSIGN_ROLE',
    CREATE_INVITE = 'CREATE_INVITE',
    CREATE_CATEGORY = 'CREATE_CATEGORY',
    DELETE_USER = 'DELETE_USER',
    E2EE_PASSWORD = 'E2EE_PASSWORD'
}
